In [1]:
import pandas as pd
from pathlib import Path

parquet_path = Path(r"D:\tfg_finance\mi_proyecto_datos\local_db\processed\chicago_fed\call-reports-balance-sheets-jan2026.parquet")

df = pd.read_parquet(parquet_path)
df.head()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2548675 entries, 0 to 2548674
Columns: 190 entries, id_rssd to tot_sav_dep
dtypes: datetime64[ns](1), float64(177), int32(1), object(11)
memory usage: 3.6+ GB

In [2]:
df = pd.read_parquet(parquet_path)

# Ver la lista completa de nombres
print(df.columns)                      # Index(...)
print(df.columns.tolist())            # lista de strings

Index(['id_rssd', 'date', 'id_rssd_hd_off', 'id_cusip', 'id_thrift',
       'id_aba_prim', 'id_fdic_cert', 'id_occ', 'state_cd', 'ent_type_cd',
       ...
       'transaction_dep', 'uninsured_time_dep', 'ust_sec_1y_3y',
       'ust_sec_3mo_12mo', 'ust_sec_3mo_less', 'ust_sec_3y_5y',
       'ust_sec_5y_15y', 'ust_sec_over_15y', 'net_hedging', 'tot_sav_dep'],
      dtype='object', length=190)
['id_rssd', 'date', 'id_rssd_hd_off', 'id_cusip', 'id_thrift', 'id_aba_prim', 'id_fdic_cert', 'id_occ', 'state_cd', 'ent_type_cd', 'assets', 'cash', 'securities', 'ln_tot_gross', 'ln_tot', 'llres', 'trad_ass', 'ffrepo_ass', 'ffsold', 'repo_purch', 'fixed_ass', 'oreo', 'oth_assets', 'oth_assets_alt', 'demand_deposits', 'time_deposits', 'deposits', 'ffrepo_liab', 'ffpurch', 'repo_sold', 'trad_liab', 'othbor_liab', 'subdebt', 'liab_oth', 'liab_tot', 'liab_tot_unadj', 'minorint', 'pref_stock', 'comm_stock', 'surplus', 'retain_earn', 'equity', 'ln_re', 'ln_fi', 'ln_dep_inst', 'ln_dep_inst_dom', 'ln_oth', 'ln_cc', 'ln_ci', 'ln_cons', 'npl_tot', 'brokered_dep', 'insured_deposits', 'insured_deposits_alt', 'reg_hh_1_id', 'fin_hh_id', 'reg_dh_1_id', 'fgn_call_fam_id', 'fgn_call_cntry_cd', 'chtr_type_cd', 'nm_lgl', 'nm_short', 'reason_term_cd', 'entity_type', 'act_prim_cd', 'city', 'cntry_nm', 'state_abbr_nm', 'street_line1', 'zip_cd', 'county_cd', 'dist_frs', 'cntry_cd', 'dt_open', 'id_tax', 'id_lei', 'afssec_fv', 'brokered_dep_ge100k', 'brokered_dep_lt100k', 'dom_deposit_ib', 'dom_deposit_nib', 'domestic_dep', 'for_deposit_ib', 'for_deposit_nib', 'foreign_dep', 'gross_hedging', 'htmsec_ac', 'ln_agr', 'ln_lease', 'ln_lease_1y_3y', 'ln_lease_3mo_12mo', 'ln_lease_3mo_less', 'ln_lease_3y_5y', 'ln_lease_5y_15y', 'ln_lease_mat_1y_less', 'ln_lease_over_15y', 'nontransaction_dep', 'nontransaction_sav_dep', 'other_mbs_3y_less', 'other_mbs_3y_more', 'qtr_avg_assets', 'qtr_avg_ffrepo_ass', 'qtr_avg_ffrepo_liab', 'qtr_avg_fgn_dep', 'qtr_avg_ib_bal_due', 'qtr_avg_lease', 'qtr_avg_ln_agr', 'qtr_avg_ln_cc', 'qtr_avg_ln_ci', 'qtr_avg_ln_cons', 'qtr_avg_ln_fgn', 'qtr_avg_ln_othcons', 'qtr_avg_ln_othre', 'qtr_avg_ln_re', 'qtr_avg_ln_rre', 'qtr_avg_ln_tot', 'qtr_avg_mbs', 'qtr_avg_oth_sec', 'qtr_avg_othbor_liab', 'qtr_avg_sav_dep_dom', 'qtr_avg_securities', 'qtr_avg_time_cd_ge100k', 'qtr_avg_time_dep_ge100k', 'qtr_avg_time_dep_gt250k', 'qtr_avg_time_dep_le250k', 'qtr_avg_time_dep_lt100k', 'qtr_avg_trad_ass', 'qtr_avg_trans_dep_dom', 'qtr_avg_ust_sec', 'res_loans_1y_3y', 'res_loans_3mo_12mo', 'res_loans_3mo_less', 'res_loans_3y_5y', 'res_loans_5y_15y', 'res_loans_over_15y', 'res_mbs_1y_3y', 'res_mbs_3mo_12mo', 'res_mbs_3mo_less', 'res_mbs_3y_5y', 'res_mbs_5y_15y', 'res_mbs_over_15y', 'securities_1y_3y', 'securities_3mo_12mo', 'securities_3mo_less', 'securities_3y_5y', 'securities_5y_15y', 'securities_ac', 'securities_mat_1y_less', 'securities_over_15y', 'time_cd_ge100k', 'time_dep_ge100k', 'time_dep_ge100k_1y_3y', 'time_dep_ge100k_3mo_12mo', 'time_dep_ge100k_3mo_less', 'time_dep_ge100k_over_3yr', 'time_dep_gt250k', 'time_dep_gt250k_1y_3y', 'time_dep_gt250k_3mo_12mo', 'time_dep_gt250k_3mo_less', 'time_dep_gt250k_over_3yr', 'time_dep_le250k', 'time_dep_le250k_1y_3y', 'time_dep_le250k_3mo_12mo', 'time_dep_le250k_3mo_less', 'time_dep_le250k_mat_1y_less', 'time_dep_le250k_over_3yr', 'time_dep_lt100k', 'time_dep_lt100k_1y_3y', 'time_dep_lt100k_3mo_12mo', 'time_dep_lt100k_3mo_less', 'time_dep_lt100k_mat_1y_less', 'time_dep_lt100k_over_3yr', 'time_ge100k_le250k', 'time_sav_dep', 'tot_gna_deriv_ir', 'tot_gna_deriv_ir_par', 'tot_gna_deriv_trad_ir', 'tot_gna_ir_fixed_rate_swap', 'tot_gna_ir_float_rate_swap', 'tot_swaps_int_rate', 'transaction_dep', 'uninsured_time_dep', 'ust_sec_1y_3y', 'ust_sec_3mo_12mo', 'ust_sec_3mo_less', 'ust_sec_3y_5y', 'ust_sec_5y_15y', 'ust_sec_over_15y', 'net_hedging', 'tot_sav_dep']

In [3]:
import pandas as pd
from pathlib import Path

parquet_path = Path(r"D:\tfg_finance\mi_proyecto_datos\local_db\processed\chicago_fed\call-reports-balance-sheets-jan2026.parquet")
out_path = parquet_path.with_name("call-reports-balance-sheets-jan2026-reducido.parquet")

cols = [
    "assets",
    "liab_tot",
    "cash",
    "securities",
    "trad_ass",
    "ffrepo_ass",
    "ffsold",
    "repo_purch",
    "npl_tot",
    "ln_tot_gross",
    "ln_ci",
    "res_loans_3mo_12mo",
    "res_loans_3mo_less",
    "res_loans_3y_5y",
    "res_loans_5y_15y",
    "res_loans_over_15y",
    "ffpurch",
    "repo_sold",
    "othbor_liab",
    "subdebt",
    "equity",
    "id_rssd",
    "date",        # ver nota abajo
    "ent_type_cd",
]

In [4]:
# Leer solo las columnas seleccionadas
df_small = pd.read_parquet(parquet_path, columns=cols)

# Opcional: reducción de memoria (downcast, categorías, etc.) si quieres
# df_small = reducir_memoria(df_small)  # si usas la función que te pasé antes

# Guardar Parquet reducido
df_small.to_parquet(out_path, index=False)

df_small.info(memory_usage="deep")
print(out_path)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2548675 entries, 0 to 2548674
Data columns (total 24 columns):
 #   Column              Dtype
---  ------              -----
 0   assets              float64
 1   liab_tot            float64
 2   cash                float64
 3   securities          float64
 4   trad_ass            float64
 5   ffrepo_ass          float64
 6   ffsold              float64
 7   repo_purch          float64
 8   npl_tot             float64
 9   ln_tot_gross        float64
 10  ln_ci               float64
 11  res_loans_3mo_12mo  float64
 12  res_loans_3mo_less  float64
 13  res_loans_3y_5y     float64
 14  res_loans_5y_15y    float64
 15  res_loans_over_15y  float64
 16  ffpurch             float64
 17  repo_sold           float64
 18  othbor_liab         float64
 19  subdebt             float64
 20  equity              float64
 21  id_rssd             int32
 22  date                datetime64[ns]
 23  ent_type_cd         float64
dtypes: datetime64[ns](1), float64(22), int32(1)
memory usage: 457.0 MB
D:\tfg_finance\mi_proyecto_datos\local_db\processed\chicago_fed\call-reports-balance-sheets-jan2026-reducido.parquet

In [5]:
import pandas as pd
from pathlib import Path

path_in = Path(r"D:\tfg_finance\mi_proyecto_datos\local_db\processed\chicago_fed\call-reports-balance-sheets-jan2026-reducido.parquet")
path_out = path_in.with_name("call-reports-balance-sheets-1996on.parquet")

df = pd.read_parquet(path_in)

# Filtro: fechas >= 1996-01-01
cutoff = pd.Timestamp("1996-01-01")
df_1996on = df[df["date"] >= cutoff]

df_1996on.info(memory_usage="deep")
df_1996on["date"].min(), df_1996on["date"].max()

<class 'pandas.core.frame.DataFrame'>
Index: 848866 entries, 153 to 2548674
Data columns (total 24 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   assets              848854 non-null  float64
 1   liab_tot            848854 non-null  float64
 2   cash                848854 non-null  float64
 3   securities          848854 non-null  float64
 4   trad_ass            848854 non-null  float64
 5   ffrepo_ass          848855 non-null  float64
 6   ffsold              663874 non-null  float64
 7   repo_purch          663874 non-null  float64
 8   npl_tot             848854 non-null  float64
 9   ln_tot_gross        848854 non-null  float64
 10  ln_ci               848854 non-null  float64
 11  res_loans_3mo_12mo  797843 non-null  float64
 12  res_loans_3mo_less  797843 non-null  float64
 13  res_loans_3y_5y     797843 non-null  float64
 14  res_loans_5y_15y    797843 non-null  float64
 15  res_loans_over_15y  797843 non-null  float64
 16  ffpurch             663874 non-null  float64
 17  repo_sold           663874 non-null  float64
 18  othbor_liab         848854 non-null  float64
 19  subdebt             848854 non-null  float64
 20  equity              848854 non-null  float64
 21  id_rssd             848866 non-null  int32
 22  date                848866 non-null  datetime64[ns]
 23  ent_type_cd         848752 non-null  float64
dtypes: datetime64[ns](1), float64(22), int32(1)
memory usage: 158.7 MB

(Timestamp('1996-01-01 00:00:00'), Timestamp('2025-10-01 00:00:00'))

In [6]:
df_1996on.to_parquet(path_out, index=False)
print(path_out)

D:\tfg_finance\mi_proyecto_datos\local_db\processed\chicago_fed\call-reports-balance-sheets-1996on.parquet

In [7]:
df_bal = pd.read_parquet(
    r"D:\tfg_finance\mi_proyecto_datos\local_db\processed\chicago_fed\call-reports-balance-sheets-1996on.parquet"
)
df_bal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 848866 entries, 0 to 848865
Data columns (total 24 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   assets              848854 non-null  float64
 1   liab_tot            848854 non-null  float64
 2   cash                848854 non-null  float64
 3   securities          848854 non-null  float64
 4   trad_ass            848854 non-null  float64
 5   ffrepo_ass          848855 non-null  float64
 6   ffsold              663874 non-null  float64
 7   repo_purch          663874 non-null  float64
 8   npl_tot             848854 non-null  float64
 9   ln_tot_gross        848854 non-null  float64
 10  ln_ci               848854 non-null  float64
 11  res_loans_3mo_12mo  797843 non-null  float64
 12  res_loans_3mo_less  797843 non-null  float64
 13  res_loans_3y_5y     797843 non-null  float64
 14  res_loans_5y_15y    797843 non-null  float64
 15  res_loans_over_15y  797843 non-null  float64
 16  ffpurch             663874 non-null  float64
 17  repo_sold           663874 non-null  float64
 18  othbor_liab         848854 non-null  float64
 19  subdebt             848854 non-null  float64
 20  equity              848854 non-null  float64
 21  id_rssd             848866 non-null  int32
 22  date                848866 non-null  datetime64[ns]
 23  ent_type_cd         848752 non-null  float64
dtypes: datetime64[ns](1), float64(22), int32(1)
memory usage: 152.2 MB

In [8]:
import pandas as pd
from pathlib import Path

# Paths
path_bal = Path(r"D:\tfg_finance\mi_proyecto_datos\local_db\processed\chicago_fed\call-reports-balance-sheets-1996on.parquet")
path_inc = Path(r"D:\tfg_finance\mi_proyecto_datos\local_db\processed\chicago_fed\call-reports-income-statements-1996on.parquet")

# Cargar balances
df_bal = pd.read_parquet(path_bal)

# Cargar solo claves + columna necesaria del income
cols_inc = ["id_rssd", "date", "ytdnet_operating_earn"]
df_inc = pd.read_parquet(path_inc, columns=cols_inc)

In [9]:
# Asegurar tipos
df_bal["date"] = pd.to_datetime(df_bal["date"])
df_inc["date"] = pd.to_datetime(df_inc["date"])

df_bal["id_rssd"] = df_bal["id_rssd"].astype("int32")
df_inc["id_rssd"] = df_inc["id_rssd"].astype("int32")

# Orden (no es obligatorio, pero ayuda a revisar)
df_bal = df_bal.sort_values(["id_rssd", "date"])
df_inc = df_inc.sort_values(["id_rssd", "date"])

In [10]:
path_merged = path_bal.with_name("call-reports-balances-plus-income-1996on.parquet")

df_merged = df_bal.merge(
    df_inc,
    on=["id_rssd", "date"],
    how="left",
    validate="one_to_one",   # avisa si hay duplicados en las claves
)

df_merged.info(memory_usage="deep")
df_merged.to_parquet(path_merged, index=False)
print(path_merged)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 848866 entries, 0 to 848865
Data columns (total 25 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   assets                 848854 non-null  float64
 1   liab_tot               848854 non-null  float64
 2   cash                   848854 non-null  float64
 3   securities             848854 non-null  float64
 4   trad_ass               848854 non-null  float64
 5   ffrepo_ass             848855 non-null  float64
 6   ffsold                 663874 non-null  float64
 7   repo_purch             663874 non-null  float64
 8   npl_tot                848854 non-null  float64
 9   ln_tot_gross           848854 non-null  float64
 10  ln_ci                  848854 non-null  float64
 11  res_loans_3mo_12mo     797843 non-null  float64
 12  res_loans_3mo_less     797843 non-null  float64
 13  res_loans_3y_5y        797843 non-null  float64
 14  res_loans_5y_15y       797843 non-null  float64
 15  res_loans_over_15y     797843 non-null  float64
 16  ffpurch                663874 non-null  float64
 17  repo_sold              663874 non-null  float64
 18  othbor_liab            848854 non-null  float64
 19  subdebt                848854 non-null  float64
 20  equity                 848854 non-null  float64
 21  id_rssd                848866 non-null  int32
 22  date                   848866 non-null  datetime64[ns]
 23  ent_type_cd            848752 non-null  float64
 24  ytdnet_operating_earn  848853 non-null  float64
dtypes: datetime64[ns](1), float64(23), int32(1)
memory usage: 158.7 MB
D:\tfg_finance\mi_proyecto_datos\local_db\processed\chicago_fed\call-reports-balances-plus-income-1996on.parquet

In [11]:
import pandas as pd
from pathlib import Path

path = Path(r"D:\tfg_finance\mi_proyecto_datos\local_db\processed\chicago_fed\call-reports-balances-plus-income-1996on.parquet")
df = pd.read_parquet(path)

# Asegurar que 'date' es datetime
df["date"] = pd.to_datetime(df["date"])

# 1) Fecha del fin de trimestre (por ejemplo 1996-03-31, 1996-06-30, etc.)
df["qdate"] = df["date"].dt.to_period("Q").dt.to_timestamp("Q")  # fin de trimestre[web:322][web:323][web:321]

# 2) (Opcional) Etiqueta de trimestre tipo '1996Q1'
df["quarter"] = df["date"].dt.to_period("Q").astype(str)  # '1996Q1', '1996Q2', ...[web:324][web:325]

df[["id_rssd", "date", "qdate", "quarter"]].head()

   id_rssd       date      qdate quarter
0       37 1996-01-01 1996-03-31  1996Q1
1       37 1996-04-01 1996-06-30  1996Q2
2       37 1996-07-01 1996-09-30  1996Q3
3       37 1996-10-01 1996-12-31  1996Q4
4       37 1997-01-01 1997-03-31  1997Q1

In [13]:

path_in = Path(r"D:\tfg_finance\mi_proyecto_datos\local_db\processed\chicago_fed\call-reports-balances-plus-income-1996on.parquet")
path_out = path_in.with_name("call-reports-balances-plus-income-q1996on.parquet")

df = pd.read_parquet(path_in)

# Asegurar que 'date' es datetime
df["date"] = pd.to_datetime(df["date"])

# Crear la fecha de fin de trimestre
qdate = df["date"].dt.to_period("Q").dt.to_timestamp("Q")  # p.ej. 1996-03-31, 1996-06-30...[web:352][web:321][web:355][web:363]

# Sustituir la columna 'date' por la trimestral
df["date"] = qdate

df[["id_rssd", "date"]].head()
df["date"].sort_values().unique()[:10]  # para ver los trimestres resultantes

<DatetimeArray>
['1996-03-31 00:00:00', '1996-06-30 00:00:00', '1996-09-30 00:00:00',
 '1996-12-31 00:00:00', '1997-03-31 00:00:00', '1997-06-30 00:00:00',
 '1997-09-30 00:00:00', '1997-12-31 00:00:00', '1998-03-31 00:00:00',
 '1998-06-30 00:00:00']
Length: 10, dtype: datetime64[ns]

In [14]:
df.to_parquet(path_out, index=False)
print(path_out)

D:\tfg_finance\mi_proyecto_datos\local_db\processed\chicago_fed\call-reports-balances-plus-income-q1996on.parquet

In [15]:
path = Path(r"D:\tfg_finance\mi_proyecto_datos\local_db\processed\chicago_fed\call-reports-balances-plus-income-q1996on.parquet")
panel = pd.read_parquet(path)

# Por seguridad, aseguramos tipos básicos
panel["date"] = pd.to_datetime(panel["date"])
panel["id_rssd"] = panel["id_rssd"].astype("int32")

# Para evitar problemas de división por 0, usamos .where(...)
eps = 1e-9
assets_safe = panel["assets"].where(panel["assets"] != 0, eps)
ln_tot_safe = panel["ln_tot_gross"].where(panel["ln_tot_gross"] != 0, eps)

In [16]:
# CAR: equity / assets
panel["CAR"] = panel["equity"] / assets_safe

# LIQ: (cash + securities + trad_ass + ffrepo_ass + ffsold + repo_purch) / assets
panel["LIQ"] = (
    panel["cash"]
    + panel["securities"]
    + panel["trad_ass"]
    + panel["ffrepo_ass"]
    + panel["ffsold"]
    + panel["repo_purch"]
) / assets_safe

# NPL: npl_tot / ln_tot_gross
panel["NPL"] = panel["npl_tot"] / ln_tot_safe

# CIL: ln_ci / assets
panel["CIL"] = panel["ln_ci"] / assets_safe

# HOL: (res_loans_3mo_less + res_loans_3y_5y + res_loans_5y_15y + res_loans_over_15y) / assets
panel["HOL"] = (
    panel["res_loans_3mo_less"]
    + panel["res_loans_3y_5y"]
    + panel["res_loans_5y_15y"]
    + panel["res_loans_over_15y"]
) / assets_safe

# WFUND: (ffpurch + repo_sold + othbor_liab + subdebt) / assets
panel["WFUND"] = (
    panel["ffpurch"]
    + panel["repo_sold"]
    + panel["othbor_liab"]
    + panel["subdebt"]
) / assets_safe

# ROA: ytdnet_operating_earn / assets
panel["ROA"] = panel["ytdnet_operating_earn"] / assets_safe

In [17]:
panel.info(memory_usage="deep")

out_path = path.with_name("Variables_MES_banco-trimestre.parquet")
panel.to_parquet(out_path, index=False)
print(out_path)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 848866 entries, 0 to 848865
Data columns (total 32 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   assets                 848854 non-null  float64
 1   liab_tot               848854 non-null  float64
 2   cash                   848854 non-null  float64
 3   securities             848854 non-null  float64
 4   trad_ass               848854 non-null  float64
 5   ffrepo_ass             848855 non-null  float64
 6   ffsold                 663874 non-null  float64
 7   repo_purch             663874 non-null  float64
 8   npl_tot                848854 non-null  float64
 9   ln_tot_gross           848854 non-null  float64
 10  ln_ci                  848854 non-null  float64
 11  res_loans_3mo_12mo     797843 non-null  float64
 12  res_loans_3mo_less     797843 non-null  float64
 13  res_loans_3y_5y        797843 non-null  float64
 14  res_loans_5y_15y       797843 non-null  float64
 15  res_loans_over_15y     797843 non-null  float64
 16  ffpurch                663874 non-null  float64
 17  repo_sold              663874 non-null  float64
 18  othbor_liab            848854 non-null  float64
 19  subdebt                848854 non-null  float64
 20  equity                 848854 non-null  float64
 21  id_rssd                848866 non-null  int32
 22  date                   848866 non-null  datetime64[ns]
 23  ent_type_cd            848752 non-null  float64
 24  ytdnet_operating_earn  848853 non-null  float64
 25  CAR                    848854 non-null  float64
 26  LIQ                    663874 non-null  float64
 27  NPL                    848854 non-null  float64
 28  CIL                    848854 non-null  float64
 29  HOL                    797834 non-null  float64
 30  WFUND                  663874 non-null  float64
 31  ROA                    848853 non-null  float64
dtypes: datetime64[ns](1), float64(30), int32(1)
memory usage: 204.0 MB
D:\tfg_finance\mi_proyecto_datos\local_db\processed\chicago_fed\Variables_MES_banco-trimestre.parquet

In [18]:
panel = pd.read_parquet( r"D:\tfg_finance\mi_proyecto_datos\local_db\processed\chicago_fed\Variables_MES_banco-trimestre.parquet")
panel[["id_rssd", "date", "CAR", "LIQ", "NPL", "CIL", "HOL", "WFUND", "ROA"]].head()

,id_rssd,date,CAR,LIQ,NPL,CIL,HOL,WFUND,ROA
0,37,1996-03-31,0.144912,0.431923,0.024729,0.031619,NaN,0.0,0.004795
1,37,1996-06-30,0.146421,0.380936,0.022369,0.051399,NaN,0.0,0.009328
2,37,1996-09-30,0.154021,0.352430,0.006095,0.056966,NaN,0.0,0.015708
3,37,1996-12-31,0.153234,0.429432,0.007413,0.040727,NaN,0.0,0.018279
4,37,1997-03-31,0.149123,NaN,0.008777,0.034267,NaN,NaN,0.004092

In [19]:
import pandas as pd
from pathlib import Path

# Cargar el panel con ratios
path = Path(r"D:\tfg_finance\mi_proyecto_datos\local_db\processed\chicago_fed\Variables_MES_banco-trimestre.parquet")
panel = pd.read_parquet(path)

# Seleccionar solo las columnas que quieres exportar
cols_out = [
    "id_rssd",
    "date",
    "CAR",
    "LIQ",
    "NPL",
    "CIL",
    "HOL",
    "WFUND",
    "ROA",
]

panel_export = panel[cols_out]

# Ruta de salida CSV
csv_path = path.with_name("Variables_MES_banco-trimestre1996.csv")

# Exportar a CSV sin índice
panel_export.to_csv(csv_path, index=False)  # columns=cols_out también valdría[web:380][web:383][web:384][web:389][web:393]

print(csv_path)

D:\tfg_finance\mi_proyecto_datos\local_db\processed\chicago_fed\Variables_MES_banco-trimestre1996.csv